title: blog.fdo.cr
author: Fernando Valverde
email: fernando@fdo.cr
description: >-
  I'm Fernando and this is my captain's log, my little corner of the internet.
baseurl: ""
url: "https://blog.fdo.cr"
lang: en
logo: /assets/og_banner.png

twitter:
  username: fdocr_
  card: summary

author:
  name: Fernando Valverde
  email: fernando@fdo.cr
  twitter: fdocr_

paginate: 15
paginate_path: /page:num/

theme: null
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

